/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    FilePreviews: typeof import('./components/FilePreviews.vue')['default']
    InputMessage: typeof import('./components/InputMessage.vue')['default']
    RenameChatDialog: typeof import('./components/RenameChatDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchChatDialog: typeof import('./components/SearchChatDialog.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
