/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FilePreviews: typeof import('./components/FilePreviews.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputMessage: typeof import('./components/InputMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SideBar: typeof import('./components/sideBar.vue')['default']
  }
}
